### ISSUE TITLE
Why are pull_request events set to skip docker push in the docs?

### ISSUE THREAD

**Issue by underyx** [crazy-max/ghaction-docker-meta#43]
After going through all that trouble to run the job on PRs and come up with a beautiful little `:pr-123` tag, in all the examples the push job config says `push: ${{ github.event_name != 'pull_request' }}`. It's the same on GitHub's build-and-push action docs, too.

Why is not pushing from PRs the default? What's the workflow useful for when pushing is disabled?

**Comment by felipecrs** [comment]
I bet it's due to the permissions. When the pull request comes from a forked repo, the secrets are not available, unless you [explicitly choose to share them in the repository settings](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/).

However, there should be a way to check if the PR comes from a forked repository or not, and therefore use this condition.

Remember that the default value for `push` is actually `false`. Anything else mentioned in the docs, such as what you said, is only an example.

**Comment by crazy-max** [comment]
@underyx Yes that's exactly what @felipecrs says. That's why our examples always exclude login and push.

> unless you [explicitly choose to share them in the repository settings](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/).

I haven't had the opportunity to do this yet but I will make some tests with the new `pull_request_target` event when I have some time.

**Comment by underyx** [comment]
Thanks a lot for explaining!
